feat: initial setup
movie-web/discord-bot pull request #1
Opened 2023-09-06 12:58 UTC by castdrian

this pr aims to implement the basic boilerplate and initial feature-set of mw-bot, it will stay a draft PR until the following tasks are finished:

- [x] setup boilerplate
- [ ] implement `/available` command check title availability (autocomplete interactions)
- [ ] implement tag system (context menu interactions)

2023-09-06 13:59 UTC, mrjvs commented
pnpm is used in the v4 branch of movie-web repo. however there are still a bunch that dont use it yet.
eventually I will move them all to pnpm, but its not a requirement for now.

2023-09-07 14:38 UTC, thehairy approved these changes
approved by the djs master 3000

_I didn't really look at the code, but I know it works cuz its from you lol_

2023-09-07 14:41 UTC, binaryoverload commented on .github/workflows/docker-build.yml
> +  push:
This should probably only run on pull_request, it's not useful to have it rebuild the docker image every time you push on a random branch

2023-09-07 14:43 UTC, binaryoverload commented on .github/workflows/docker-publish.yml
> +        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
Workaround no longer required, version number can be used

```suggestion
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
```

2023-09-07 14:44 UTC, binaryoverload commented on .github/workflows/docker-publish.yml
> +        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
Outdated

```suggestion
        uses: docker/login-action@v2
```

2023-09-07 14:45 UTC, binaryoverload commented on .github/workflows/docker-publish.yml
> +        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
Outdated

```suggestion
        uses: docker/metadata-action@v4
```

2023-09-07 14:45 UTC, binaryoverload commented on .github/workflows/docker-publish.yml
> +        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
```suggestion
        uses: docker/build-push-action@v4
```

2023-09-07 14:46 UTC, binaryoverload commented on Dockerfile
> +COPY .git ./.git
What's the reasoning for including .git here?

2023-09-07 14:55 UTC, castdrian commented on Dockerfile
> +COPY .git ./.git
future proofing for a `/info` command to read out git info

2023-09-07 16:10 UTC, binaryoverload submitted a review, later dismissed
Looks solid to me, just a couple of stylistic points

We've also had a conversation in Discord about integrating our editorconfig, prettier and eslint configs into this repo - so if you could look into that that would be mint

2023-09-07 16:28 UTC, castdrian commented on src/util.ts
> +		if (!result) return;
'tis indeed unneeded, so I have shrimply removed it now

2023-09-07 20:16 UTC, castdrian commented on src/commands/info.ts
> +            url: 'discord://-/users/135081860790222848',
kek, I just copied the components from another one I made and figured his id might be the most suitable 😂, can just ditch that button overall

2023-09-07 21:44 UTC, mrjvs requested changes
lookin' good.

see the comments and a few general points:
 - please use componentBuilders instead of hardcoded json structure, then we dont have to deal with the magic numbers.
 - I think all the tags should also be triggerable by slash command. like `/tag <name>`. autocompletion would be amazing with that as well.
 
 other than that, looks very good. very hype.

2023-09-07 21:44 UTC, mrjvs commented on src/commands/info.ts
> +      description: `**Uptime:** Container started ${uptimeString}\n**Latency:** ${latency} ms\n**System:** ${osString}\n**Memory Usage:** ${memoryString}\n**Shard:** ${shardString}\n**Current Commit:
I'm not a fan of this many stats.
The only one I deem neccesary is the bot version from the package.json (which isnt in here yet)
The rest can go, the buttons on the embed can stay tho.

2023-09-07 21:44 UTC, mrjvs commented on src/commands/info.ts
> +            url: 'discord://-/users/135081860790222848',
I agree, just remove the contact button

2023-09-07 21:44 UTC, mrjvs commented on src/declarations.d.ts
> +declare module 'last-commit-log';
seems like this can go if the stats also go

2023-09-07 21:44 UTC, mrjvs commented on src/main.ts
> +if (!config.discordToken) process.exit(0);
this line is impossible to be triggered, discordToken cant be falsy

2023-09-07 21:44 UTC, mrjvs commented on src/tsconfig.json
> +  },
I think its wise to enable strict mode, if its not already

2023-09-07 21:44 UTC, mrjvs commented on src/util.ts
> +        }
I recommend using a lookup map here, then you can just do `sourceStatus.status = yourMapName[e.status];`

2023-09-07 21:44 UTC, mrjvs commented on src/util.ts
> +      icon_url: `https://github.com/movie-web/movie-web/blob/dev/public/android-chrome-512x512.png?raw=true`,
use production deployment of movie-web here: https://movie-web.app/android-chrome-512x512.png

2023-09-07 21:44 UTC, mrjvs commented on src/util.ts
> +    // eslint-disable-next-line no-negated-condition
just disable this rule, its dumb

2023-09-07 21:44 UTC, mrjvs commented on Dockerfile
> +COPY --from=build /home/node/app/dist ./dist
this also copies over dev dependencies, we probably want to only have runtime dependencies in production layer

2023-09-07 21:44 UTC, mrjvs commented on src/config.ts
> +  tagRefreshUrl: z.string(),
I would give the tagrefreshurl a default, you can default it to the file on the master branch github repo.

2023-09-07 21:46 UTC, castdrian commented
okidoki, will have it all adressed shortly

2023-09-07 23:23 UTC, castdrian commented
I believe all desired changes were implemented

2023-09-08 18:01 UTC, mrjvs requested changes
this a few more, almost done

2023-09-08 18:12 UTC, castdrian commented on Dockerfile
>  RUN yarn run build
ah true, I guess the only somewhat good solution is to not copy node modules and instead run install a second time in the last layer

2023-09-08 18:12 UTC, mrjvs commented on Dockerfile
>  RUN yarn run build
yea :+1:

2023-09-08 18:26 UTC, castdrian commented
okidoki, I believe me has dunnit

2023-09-08 18:29 UTC, mrjvs requested changes

2023-09-08 18:29 UTC, mrjvs commented on Dockerfile
> +RUN yarn install --frozen-lockfile --production
this would reinstall all packages for every changed line, try this:

```suggestion
ENV NODE_ENV=production
COPY yarn.lock package.json ./
RUN yarn install --frozen-lockfile --production
COPY --from=build /home/node/app/dist ./dist
```

2023-09-08 18:32 UTC, castdrian commented on Dockerfile
> +RUN yarn install --frozen-lockfile --production
okidoki done, github marked as outdated suggestion so couldn't autoapply :angery:

2023-09-08 18:33 UTC, mrjvs approved these changes

2023-09-08 18:33 UTC, merged

2023-09-08 18:33 UTC, mrjvs commented
thanks for the work, looks great :)

2023-09-08 18:34 UTC, castdrian commented
:D