edit tags
movie-web/discord-bot pull request #16
Opened 2023-11-17 07:12 UTC by TheScreechingBagel

edited a few and added an apps tag

2023-11-17 07:13 UTC, TheScreechingBagel commented
idk if linking fmhy & uBO is too bold

2023-11-17 11:55 UTC, binaryoverload requested changes

2023-11-17 11:55 UTC, binaryoverload commented on src/tags.toml
> +Find your language in the sidebar and look under the Streaming section. [Use this adblocker!](<https://ublockrigin.com>)
```suggestion
Find your language in the sidebar and look under the Streaming section. [Use this adblocker!](<https://ublockorigin.com>)
```

2023-11-17 11:55 UTC, binaryoverload commented on src/tags.toml
> +<https://fmhy.pages.dev/non-english>
```suggestion
Here is a list of non-English sites: <https://fmhy.pages.dev/non-english>
```

2023-11-17 11:56 UTC, binaryoverload commented
I don't think linking fmhy & uBO is bold, although I suggested removing the 🏴‍☠️ reference and corrected the uBlock URL

2023-11-17 18:52 UTC, TheScreechingBagel commented on src/tags.toml
maybe a better link/message for devs?

2023-11-18 19:28 UTC, binaryoverload approved these changes

2023-11-18 19:37 UTC, merged