feat: tags 2: electric boogalo
movie-web/discord-bot pull request #2
Opened 2023-09-09 15:33 UTC by castdrian

this pr:

- fixes an error handling oversight (lol) and cleans up some stuff
- introduces a very pog very great extended tag system that allows message embeds and components
- implements tag validation using zod

2023-09-09 20:12 UTC, binaryoverload requested changes

2023-09-09 20:12 UTC, binaryoverload commented on src/config.ts
> +}
Since we're using Zod here, it would make sense to infer the type from the schema

2023-09-12 19:36 UTC, mrjvs requested changes

2023-09-12 19:36 UTC, mrjvs commented on Dockerfile
>  ENV NODE_ENV=production
please add `EXPOSE 8080` above the env line

2023-09-12 19:36 UTC, mrjvs commented on src/commands/status.ts
> +      ];
I don't think its a good idea to start this community list right now. remove the button for now

2023-09-12 19:36 UTC, mrjvs commented on src/commands/tags.ts
> +          });
can the follow up message be a reply to the original message instead?
then you won't need to ping the original message author either.

2023-09-12 19:36 UTC, mrjvs commented on package.json
>      "build": "tsc -b src",
the build script will also need to copy over the tags.toml and mw-urls.txt to the correct location

2023-09-12 19:36 UTC, mrjvs commented on src/config.ts
> +export const mwUrls = readFileSync('./src/mw-urls.txt', 'utf8').split('\n');
for both file reads. make sure you use path.join and __dirname. to prevent using relative paths

using relative paths is relative to the working directory. meaning there is a different if I do `node dist/index.js` and `node index.js`. one works while the other one doesnt.

2023-09-12 19:36 UTC, mrjvs commented on .github/workflows/linting_test.yml
> +        node-version: [20]
I dont think building on multiple node versions is needed. itll all build to the same output.
you can just hardcode the node version

2023-09-12 19:38 UTC, mrjvs commented on Dockerfile
>  COPY src/tags.toml ./src/tags.toml
this line can be removed when other comments have been resolved

2023-09-12 19:40 UTC, castdrian commented on src/commands/tags.ts
> +          });
unfortunately this is (BLEH) not possible due to the nature of how interactions work, they are just webhooks under the hood, and for whatever reason a followup is always an inline reply to the interaction response, which is unfortunate (and also stupid because discord)

2023-09-12 19:41 UTC, mrjvs commented on src/commands/tags.ts
> +          });
cant you just post a normal message?

2023-09-12 19:42 UTC, castdrian commented on .github/workflows/linting_test.yml
> +        node-version: [20]
figured as much, didn't think matrix was needed but I just copied what the pnpm website provided, will hardcode

2023-09-12 19:45 UTC, castdrian commented on src/commands/tags.ts
> +          });
you can, but that would require additional permissions to the bot user since that goes through the ws gateway and it would have the possibility to fail, whereas an interaction response always goes through, so if you're fine with that trade-off that is doable

2023-09-12 19:47 UTC, mrjvs commented on src/commands/tags.ts
> +          });
if it fails you can just do an interaction follow up with an error message. and the more permissions is no issue for me.
(also sending messages doesnt go through gateway? its a rest endpoint?)

2023-09-12 19:57 UTC, castdrian commented on src/commands/tags.ts
> +          });
the errors happen automatically thanks to the handler, and you are correct it was a communication error on my part I meant to say it requires additional data from the  identify event, value 0 for gateway intents is usually fine, but there can be funny instances of partial data so for some cases, like these it's recomended to receive and cache more data from the ws, don't think it matters much though, just wanted to clarify that I am an idiot bot not stupid

2023-09-13 12:44 UTC, mrjvs requested changes

2023-09-13 12:44 UTC, mrjvs commented on Dockerfile
>  COPY src/tags.toml ./src/tags.toml
```suggestion
```

2023-09-13 12:45 UTC, mrjvs approved these changes

2023-09-13 12:47 UTC, merged