feat: update deps and add more details to embed
movie-web/discord-bot pull request #23
Opened 2024-01-05 14:50 UTC by castdrian

- updates deps including /providers
- satisfies @thehairy's OCD
- shows season and episode that is being checked

2024-01-05 15:12 UTC, binaryoverload approved these changes

2024-01-07 17:33 UTC, mrjvs requested changes
Looks good. Can we maybe possibly also add the "sent by <@...>" to tags. It should be a oneliner and its been on the todo list for a while?

2024-01-07 17:33 UTC, mrjvs commented on package.json
> +    "copy": "cp src/tags.toml dist/tags.toml && cp src/mw-urls.txt dist/mw-urls.txt",
duplicate key?

2024-01-07 17:41 UTC, castdrian commented on package.json
> +    "copy": "cp src/tags.toml dist/tags.toml && cp src/mw-urls.txt dist/mw-urls.txt",
huh lol, will get rid off, must be a weird rebase remnant or something

2024-01-07 17:42 UTC, castdrian commented
> Looks good. Can we maybe possibly also add the "sent by <@...>" to tags. It should be a oneliner and its been on the todo list for a while?

will do in a min, /prov8ders has a new release anyway so can bump it up again as well

2024-01-07 17:59 UTC, castdrian commented on package.json
> +    "copy": "cp src/tags.toml dist/tags.toml && cp src/mw-urls.txt dist/mw-urls.txt",
hm, not actually duplicate in the file itself, seems to be weird github diff nonsense

2024-01-09 09:13 UTC, thehairy requested changes
Whats with all the nonempty() replaces, was it removed?
imo nonempty() makes more sense than min(1)

2024-01-09 09:17 UTC, castdrian commented
> Whats with all the nonempty() replaces, was it removed? imo nonempty() makes more sense than min(1)

deprecated

2024-01-09 09:18 UTC, thehairy approved these changes

2024-01-09 09:33 UTC, binaryoverload submitted a review, later dismissed

2024-01-11 17:56 UTC, mrjvs approved these changes

2024-01-11 17:56 UTC, merged