Remove References to Original Site
movie-web/discord-bot pull request #31
Opened 2024-03-12 19:17 UTC by TecEash1

- Use community hosted instances

2024-03-12 19:23 UTC, binaryoverload requested changes
Thanks for these

Could you post some screenshots of what the modified commands look like please?

2024-03-12 19:23 UTC, binaryoverload commented on src/commands/status.ts
>            const { ok } = await fetch(url).catch(() => ({ ok: false }));
You can use `/ping.txt` and make sure it receives "pong" as content

2024-03-12 19:31 UTC, TecEash1 commented on src/commands/status.ts
>            const { ok } = await fetch(url).catch(() => ({ ok: false }));
Not sure what you mean here... sorry 😅

2024-03-12 19:37 UTC, binaryoverload commented on src/commands/status.ts
>            const { ok } = await fetch(url).catch(() => ({ ok: false }));
On each movie-web instance, there is a file called "ping.txt" which contains the text "pong"

With this fetch call, we could do something like `url + "/ping.txt"` and check the response is "pong"

https://mw.lonelil.ru/ping.txt for example

2024-03-12 19:38 UTC, binaryoverload commented
> > Thanks for these
> > Could you post some screenshots of what the modified commands look like please?
> 
> Sure,
> 
> <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/92249532/312212670-6bc7b970-de61-4da5-9cf0-03982a8424e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI0NjcsIm5iZiI6MTcxMDI3MjE2NywicGF0aCI6Ii85MjI0OTUzMi8zMTIyMTI2NzAtNmJjN2I5NzAtZGU2MS00ZGE1LTljZjAtMDM5ODJhODQyNGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTM4YTUwMTIxZGMzMDY3M2EyMzE1MjMzMTg5Yjk1NDI0YTIzNTQwYmUyZDJjYTU1MmVjZjU2NDYxZGUzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2J71xWnnO2-5GhG6zTvkYhQcxUv5_UKi5eBnG-YasU"> <img alt="image" width="596" src="https://private-user-images.githubusercontent.com/92249532/312212721-5cb470a1-0117-49df-895f-2bb377e4cd0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI0NjcsIm5iZiI6MTcxMDI3MjE2NywicGF0aCI6Ii85MjI0OTUzMi8zMTIyMTI3MjEtNWNiNDcwYTEtMDExNy00OWRmLTg5NWYtMmJiMzc3ZTRjZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3OGEzYTg4MmY2YmI3MTFhM2ZkZDVmMzBlYTVkOTEwY2FhZjYzZWExZGI0MDEyMWM1OTVhZWVmMmM2OTJmOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOj7ePLT8HIbJjmClHBE8CozTfPQhsaIcTcYgLHR5fc"> <img alt="image" width="229" src="https://private-user-images.githubusercontent.com/92249532/312213033-cd6ae192-cd74-41d0-af59-4b8290cef953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI0NjcsIm5iZiI6MTcxMDI3MjE2NywicGF0aCI6Ii85MjI0OTUzMi8zMTIyMTMwMzMtY2Q2YWUxOTItY2Q3NC00MWQwLWFmNTktNGI4MjkwY2VmOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZmZmMjVlZTIwMzU3Nzk1MWQ3YjVlYTY1YWE1MGIxNDdkZmE4ZWIwOGE4MDcwNjQ0NmUwNTRiMGIyY2JjYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uXkqI0zv1OTjc71-ude0WZZ_IkhZc9IpTilu9nDWi9w"> <img alt="image" width="119" src="https://private-user-images.githubusercontent.com/92249532/312213229-6f69e931-1cc1-4dae-8e31-0b31716d3f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzI0NjcsIm5iZiI6MTcxMDI3MjE2NywicGF0aCI6Ii85MjI0OTUzMi8zMTIyMTMyMjktNmY2OWU5MzEtMWNjMS00ZGFlLThlMzEtMGIzMTcxNmQzZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE5MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMjM3NGY2NGNiODhmZjYxZDNmNjgzYzBjOTFiNmMxMjBmM2FhZDg5YWM2OTBjYjQzMjZjNDljYzcwMjM2YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.777PVjSH4cI5-M7-OqvPjvDAqUZC2kX1-BAZuAJ3nvg">

Great! Thanks

For the "mw status" page, could we put the status at the start of the line so that they line up?

2024-03-12 20:22 UTC, TecEash1 commented on src/commands/status.ts
>            const { ok } = await fetch(url).catch(() => ({ ok: false }));
ah gotcha, ill try switch the bot to use that method

2024-03-12 20:39 UTC, castdrian requested changes

2024-03-12 20:39 UTC, castdrian commented on package.json
> +  "version": "1.6.0",
I don't think this warrants a minor bump, patch seems sufficient here

2024-03-12 20:39 UTC, castdrian commented on src/commands/status.ts
> +      const filteredMwUrls = mwUrls.filter((url) => url.trim() !== 'https://movie-web.x');
this seems entirely redundant, just remove the line from the text file instead

2024-03-12 20:39 UTC, castdrian commented on src/listeners/client/ready.ts
> -      () => this.container.client.user?.setActivity({ type: ActivityType.Watching, name: 'movie-web.app' }),
just removing the tld here is fine, no need to artificially increase the text length

2024-03-12 20:39 UTC, castdrian commented on src/util.ts
> +      description: `Please note that the [**movie-web.x**](https://movie-web.x/) is only accessible using Brave, Opera or installing an [**extension**](https://unstoppabledomains.com/extension) to re
Honestly this feels like it should just stay in the docs, feels like bloat to have in there

2024-03-12 20:44 UTC, TecEash1 commented on src/commands/status.ts
> +      const filteredMwUrls = mwUrls.filter((url) => url.trim() !== 'https://movie-web.x');
It is also sent when the 'Watch on movie-web' Button is selected via the ``/available`` command, so that it why I kept it there.

2024-03-12 20:54 UTC, TecEash1 commented
> For the "mw status" page, could we put the status at the start of the line so that they line up?

Sure, I have done that now:

<img width="233" alt="image" src="https://github.com/movie-web/discord-bot/assets/92249532/7d84aaa4-9363-4e79-b8b3-354ec0188747">

2024-03-12 23:33 UTC, binaryoverload requested changes
Looks good

I think we can remove https://movie-web.x from here in general 

It's a niche instance and will remain in the docs, but I think will cause confusion in the bot side

2024-03-13 00:24 UTC, TecEash1 commented
> It's a niche instance and will remain in the docs, but I think will cause confusion in the bot side

Just done that now :) 

Just a note I am pretty sure, after checking the commit multiple times that it should work, however I edited it on mobile and was I was unable to test the edited code where I removed movie-web.x, so *if there is potentially an error I am sorry about that…*

2024-03-13 08:45 UTC, castdrian approved these changes

2024-03-15 17:10 UTC, TecEash1 commented
Just a note upon updating the providers sometimes the file URL is logged in the console...

2024-03-15 17:16 UTC, JorrinKievit commented
> Just a note upon updating the providers sometimes the file URL is logged in the console...

*It's a feature*

2024-03-17 13:32 UTC, TecEash1 commented
Btw that commit, overrides the console.log function blocking the video URLs from being logged in the console. 

Also, I noticed that if the ``/available`` embed (with the button) is deleted by someone before the 60 seconds is up the bot will crash. So I added anti-crash scripts to prevent this. However, they also prevent other errors as well.

2024-03-17 15:43 UTC, castdrian requested changes

2024-03-17 15:43 UTC, castdrian commented on src/consoleOverride.ts
> +};
This besides being absolutely useless is rather horrifying. Do not mutate node apis. This has no practical use whatsoever.

2024-03-17 15:43 UTC, castdrian commented on src/main.ts
> +});
This is a very bad practice. Exceptions should be handled where they occur, furthermore this prevents the node process from exiting when confronted with an unhandled rejection.

2024-03-17 15:44 UTC, JorrinKievit commented on src/consoleOverride.ts
> +};
Tbf this is a providers library bug, so feel free to PR the fix there

2024-03-17 15:54 UTC, TecEash1 commented on src/consoleOverride.ts
> +};
https://github.com/movie-web/providers/pull/117 Just done that now

2024-03-17 15:58 UTC, TecEash1 commented on src/main.ts
> +});
How should the bot handle these types of errors then? As it is an API error thrown by discord.

2024-03-17 16:12 UTC, TecEash1 commented on src/consoleOverride.ts
> +};
Hi, noticed this was merged. Sorry for asking, but how would I go about integrating this into the bot? I noticed the npm package is still on the previous version.

2024-03-19 08:43 UTC, JorrinKievit commented on src/consoleOverride.ts
> +};
We do releases once every while. But if this is blocking then we maybe should do one

2024-03-19 16:08 UTC, TecEash1 commented on src/consoleOverride.ts
> +};
Yea I think it’s unfortunately blocking it, without the release removing the consoleOverride file would cause the links to be logged in the console.

2024-03-19 18:13 UTC, TecEash1 commented on src/consoleOverride.ts
> +};
Awesome, thanks!

2024-03-19 19:18 UTC, castdrian approved these changes

2024-03-19 19:36 UTC, binaryoverload approved these changes

2024-03-19 19:36 UTC, merged